#!/bin/bash
# -------------------------------------------------------------------
# runtests
#
# Copyright (c) 2004 Simon Southwell. All rights reserved
#
# -------------------------------------------------------------------

#

testlist="mmu_fault_traps" # fop"

for testname in $testlist
do
    if [ "$1" != "nc" ] 
    then
        ./compile_c $testname nowarn
    fi

    if ~/workspace/sparcv8/bin/sparcv8_runelf -f ${testname}.aout
    then
        echo "Test '$testname' passed."
    else
        echo "Test $testname failed! ***"
    fi
done
