#!/bin/bash
# -------------------------------------------------------------------
# runtests
#
# Copyright (c) 2004 Simon Southwell. All rights reserved
#
# -------------------------------------------------------------------

#

testlist="fbfcc fld"

for testname in $testlist
do
    if [ "$1" != "nc" ] 
    then
        ./compile $testname nowarn
    fi

    if ../sparc_iss -f ${testname}.aout
    then
        echo "Test '$testname' passed."
    else
        echo "Test $testname failed! ***"
    fi
done
