// SPDX-License-Identifier: MIT
#pragma once
#include <SDL2/SDL.h>
#include <thread>
#include <atomic>
#include <condition_variable>
#include <mutex>
#include <functional>





class Display {
public:
    Display(int width, int height, int bpp, int refreshRateHz, const void* framebuffer = nullptr, bool fullscreen = false);
    ~Display();

    void start();       // Start render thread
    void enable();      // Show window and start/resume rendering
    void disable(bool hideWindow);    // Pause rendering: either hide or blank
    void stop();        // Stop thread and destroy window

    void set_framebuffer(const void* fb) {framebuffer = fb;}
    void set_resolution(int w, int h) {
        std::lock_guard<std::mutex> lock(mtx);
        width = w;
        height = h;
        resolution_changed = true;
    }

    bool isRunning() const;
    bool isEnabled() const;

    // Set callback invoked for each PS/2 Set 2 byte generated by keyboard input
    void set_key_callback(std::function<void(uint8_t)> cb) { key_callback_ = std::move(cb); }

    // Translate one SDL key event to PS/2 Set 2 bytes and invoke cb for each byte
    static void handle_key_event(const SDL_KeyboardEvent& e,
                                 const std::function<void(uint8_t)>& cb);

private:
    void renderLoop();

    int width, height, bpp, refreshRateHz;
    std::atomic<bool> resolution_changed{false};
    const void* framebuffer;

    std::thread renderThread;
    std::atomic<bool> running;
    std::atomic<bool> enabled;
    std::atomic<bool> hideWindowWhenDisabled;
    std::mutex mtx;
    std::condition_variable cv;

    std::function<void(uint8_t)> key_callback_;
    bool fullscreen_;

    // Escape sequence state (render thread only): Ctrl+A is the prefix key
    bool escape_pending_{false};
    bool a_keydown_suppressed_{false};
};